### ISSUE TITLE
Canonical URL with resource engine

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown-seo-tag#2]
I believe there is a problem here https://github.com/bridgetownrb/bridgetown-seo-tag/blob/master/lib/bridgetown-seo-tag/drop.rb#L172 ... `.url` no longer works with Resources, and should be `.relative_url`

**Comment by jaredcwhite** [comment]
If you look down at the `else` condition, it does handle `relative_url`. So it should be working (if not, could be some other issue).

**Comment by stevegeek** [comment]
Doh... I had been looking at my local installed copy of the source file, and im on v3... sorry!
