### ISSUE TITLE
OG tags generated are not complete

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown-seo-tag#3]
OG tags must have `og:title`, `og:image`, `og:type` and `og:url` to be a valid minimum set. https://ogp.me

However the SEO plugin does not include `og:type` unless on blog posts

Would be great if `og:type` would fallback to `website` when not article or specified somehow else (eg via front matter)

**Comment by jaredcwhite** [comment]
Great point! Kinda surprised Jekyll's seo plugin (on which this was originally based) never correctly included that.

**Comment by jaredcwhite** [comment]
Ah, relevant PR over there: https://github.com/jekyll/jekyll-seo-tag/pull/391
