### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by manuelgomes** [bridgetownrb/bridgetown-seo-tag#8]
Under [Setting a default image](https://github.com/bridgetownrb/bridgetown-seo-tag#setting-a-default-image) the link for "Front Matter Defaults" (https://www.bridgetownrb.com/docs/configuration/front-matter-defaults/) is a 404 on the main Bridgetown Site.

Sorry this is not a pull request with a fix, but it's not apparent to me what the correct item in the bridgetown documentation should be.

**Comment by jaredcwhite** [comment]
Ah, yeah it should actually be: https://www.bridgetownrb.com/docs/content/front-matter-defaults
